# -*- coding: utf-8 -*-
"""ZD_DataAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b1EaDemXHWixcvONPriZZNEEbJr9Qhw3
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
# Set up visual style
sns.set(style="whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)

# Load the dataset

import pandas as pd

# If you uploaded a zip file, unzip first
import zipfile

with zipfile.ZipFile("/content/Zomato Dataset.csv (1).zip", 'r') as zip_ref:
    zip_ref.extractall("/content")

# Now load CSV properly
df = pd.read_csv("/content/Zomato Dataset.csv",
                 delimiter=",",    # change to ";" or "\t" if needed
                 encoding="utf-8", # try "latin1" if utf-8 gives errors
                 low_memory=False)

print(df.shape)
print(df.columns)
df.head()

"""# Data cleaning and preprocessing ---------"""

df_copy=df.copy()

df_copy.head()

# Check number of duplicate rows
num_duplicates = df_copy.duplicated().sum()

print(f"🔍 Number of duplicate rows in dataset: {num_duplicates}")

print("Shape of dataset:", df.shape)

print("\nData Types:\n", df.dtypes)

# Standardize column names
# ---------------------------
df.columns = [col.strip().replace(" ", "_").replace("(", "").replace(")", "").lower()
              for col in df.columns]
df.tail()

# Convert order_date
df['order_date'] = pd.to_datetime(df['order_date'], format='%d-%m-%Y', errors='coerce')

# Convert time columns (hour:minute format)
df['time_orderd'] = pd.to_datetime(df['time_orderd'], format='%H:%M', errors='coerce')
df['time_order_picked'] = pd.to_datetime(df['time_order_picked'], format='%H:%M', errors='coerce')

# Drop rows with invalid times
df.dropna(subset=['time_orderd', 'time_order_picked'], inplace=True)

# Critical columns that must not be null
critical_cols = ['order_date', 'time_orderd', 'time_order_picked',
                 'weather_conditions', 'city', 'time_taken_min']
df.dropna(subset=critical_cols, inplace=True)

# drop duplicates

df.drop_duplicates(inplace=True)

df.drop(columns=["vehicle_condition"])

df.head()

"""# Basic EDA --------

**Basic Info**
"""

print("Shape of dataset:", df.shape)

# Summary Stats
df.info()

print("\nDescriptive Statistics:")
print(df.describe(include='all'))

# for numerical attributes (summary of numeric columns (count, mean, std, quartiles, min, max))
df.describe(include=np.number).T

# for categorical attributes (summary of categorical columns (count, unique, top, freq))
df.describe(include="object").T

"""handling missing values---------------------------"""

print("\nColumn-wise missing values:\n", df.isnull().sum())

# Critical columns (cannot be null)
df = df.dropna(subset=['time_orderd'])
df = df.dropna(subset=['city', 'weather_conditions'])

# Categorical columns (fill with mode)
df['road_traffic_density']=df['road_traffic_density'].fillna(df['road_traffic_density'].mode()[0])
df['festival']=df['festival'].fillna("No")

# Numeric fills
df['delivery_person_age'] = df['delivery_person_age'].fillna(df['delivery_person_age'].median())
df['delivery_person_ratings'] = df['delivery_person_ratings'].fillna(df['delivery_person_ratings'].median())
df['multiple_deliveries'] = df['multiple_deliveries'].fillna(0).astype(int)

# Verify again
print(df[['delivery_person_age','delivery_person_ratings','multiple_deliveries','festival']].isnull().sum())

df.shape

df.nunique()

# handling noise(check for outliers)
print(df[['delivery_person_age','delivery_person_ratings','multiple_deliveries','time_taken_min']].describe(include=np.number).T)

for col in ['weather_conditions','road_traffic_density','festival','city']:
    df[col] = df[col].str.strip().str.lower()
    print(f"{col}: {df[col].unique()}")
# Fix typo in city
df['city'] = df['city'].replace({'metropolitian': 'metropolitan'})

# Drop only if column exists
cols_to_drop = [
    'delivery_person_id',
    'vehicle_condition',
    'restaurant_latitude',
    'restaurant_longitude',
    'delivery_location_latitude',
    'delivery_location_longitude'
]

df = df.drop(columns=[col for col in cols_to_drop if col in df.columns])
print("Final dataset shape:", df.shape)
print("\nFinal Columns:")
for col in df.columns:
    print("-", col)

# Export cleaned dataset
df.to_csv("Zomato_Cleaned.csv", index=False)
print("\n Clean dataset exported as 'Zomato_Cleaned.csv'")